import 'package:recipe_finder_app/data/model/recipe.dart';

// Sample recipe data for testing
final sampleRecipeJson = {
  'idMeal': '52771',
  'strMeal': 'Spicy Arrabiata Penne',
  'strDrinkAlternate': '',
  'strCategory': 'Vegetarian',
  'strArea': 'Italian',
  'strInstructions':
      'Bring a large pot of water to a boil. Add kosher salt to the boiling water, then add the pasta.',
  'strMealThumb':
      'https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg',
  'strTags': 'Pasta,Curry',
  'strYoutube': 'https://www.youtube.com/watch?v=1IszT_guI08',
  'strIngredient1': 'penne rigate',
  'strIngredient2': 'olive oil',
  'strIngredient3': 'garlic',
  'strIngredient4': 'chopped tomatoes',
  'strIngredient5': 'red chile flakes',
  'strIngredient6': 'italian seasoning',
  'strIngredient7': 'basil',
  'strIngredient8': 'Parmigiano-Reggiano',
  'strIngredient9': '',
  'strIngredient10': '',
  'strIngredient11': '',
  'strIngredient12': '',
  'strIngredient13': '',
  'strIngredient14': '',
  'strIngredient15': '',
  'strIngredient16': '',
  'strIngredient17': '',
  'strIngredient18': '',
  'strIngredient19': '',
  'strIngredient20': '',
  'strMeasure1': '1 pound',
  'strMeasure2': '1/4 cup',
  'strMeasure3': '3 cloves',
  'strMeasure4': '1 tin ',
  'strMeasure5': '1/2 teaspoon',
  'strMeasure6': '1/2 teaspoon',
  'strMeasure7': '6 leaves',
  'strMeasure8': 'spinkling',
  'strMeasure9': '',
  'strMeasure10': '',
  'strMeasure11': '',
  'strMeasure12': '',
  'strMeasure13': '',
  'strMeasure14': '',
  'strMeasure15': '',
  'strMeasure16': '',
  'strMeasure17': '',
  'strMeasure18': '',
  'strMeasure19': '',
  'strMeasure20': '',
  'strSource': '',
  'strImageSource': '',
  'strCreativeCommonsConfirmed': '',
  'dateModified': '',
};

final sampleRecipe = Recipe.fromJson(sampleRecipeJson);

final sampleRecipe2Json = {
  'idMeal': '52772',
  'strMeal': 'Teriyaki Chicken',
  'strDrinkAlternate': '',
  'strCategory': 'Chicken',
  'strArea': 'Japanese',
  'strInstructions': 'Mix the ingredients and marinate chicken.',
  'strMealThumb':
      'https://www.themealdb.com/images/media/meals/teriyaki.jpg',
  'strTags': 'Meat,Chicken',
  'strYoutube': 'https://www.youtube.com/watch?v=test',
  'strIngredient1': 'chicken',
  'strIngredient2': 'soy sauce',
  'strIngredient3': 'mirin',
  'strIngredient4': 'sugar',
  'strIngredient5': '',
  'strIngredient6': '',
  'strIngredient7': '',
  'strIngredient8': '',
  'strIngredient9': '',
  'strIngredient10': '',
  'strIngredient11': '',
  'strIngredient12': '',
  'strIngredient13': '',
  'strIngredient14': '',
  'strIngredient15': '',
  'strIngredient16': '',
  'strIngredient17': '',
  'strIngredient18': '',
  'strIngredient19': '',
  'strIngredient20': '',
  'strMeasure1': '500g',
  'strMeasure2': '2 tbsp',
  'strMeasure3': '1 tbsp',
  'strMeasure4': '1 tsp',
  'strMeasure5': '',
  'strMeasure6': '',
  'strMeasure7': '',
  'strMeasure8': '',
  'strMeasure9': '',
  'strMeasure10': '',
  'strMeasure11': '',
  'strMeasure12': '',
  'strMeasure13': '',
  'strMeasure14': '',
  'strMeasure15': '',
  'strMeasure16': '',
  'strMeasure17': '',
  'strMeasure18': '',
  'strMeasure19': '',
  'strMeasure20': '',
  'strSource': '',
  'strImageSource': '',
  'strCreativeCommonsConfirmed': '',
  'dateModified': '',
};

final sampleRecipe2 = Recipe.fromJson(sampleRecipe2Json);

final sampleCategoryJson = {
  'idCategory': '1',
  'strCategory': 'Vegetarian',
  'strCategoryThumb': 'https://www.themealdb.com/images/category/vegetarian.png',
  'strCategoryDescription': 'Vegetarian recipes'
};

final sampleAreaJson = {
  'strArea': 'Italian',
};
